src/cungLaoDong/Controllers/ModulesController.cs
using Microsoft.AspNetCore.Mvc;

namespace cungLaoDong.Controllers;

public class ModulesController : Controller
{
    // GET
    public IActionResult Index()
    {
        return View();
    }
    // GET
    public IActionResult Add()
    {
        return View();
    }
}

src/cungLaoDong/Views/Modules/Add.cshtml
@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <div class="d-flex align-items-center justify-content-between">
            <h6 class="m-0 fw-bold text-primary">Thêm chức năng</h6>
            <a href="index.html" class="d-none d-sm-inline-block">
                <i class="fas fa-download fa-sm text-white-50 me-1"></i>
                Hủy
            </a>
        </div>
    </div>
    <div class="card-body">
        <div class="row align-items-center">
            <div class="col-lg-4 mb-3">
                <input type="text"
                       id="roleName"
                       class="form-control bg-light border-0"
                       placeholder="Tên chức năng">
            </div>

            <div class="col-lg-2 mb-3">
                <div class="form-check">
                    <input type="checkbox" class="form-check-input" id="xem">
                    <label class="form-check-label" for="xem">Xem</label>
                </div>
            </div>

            <div class="col-lg-2 mb-3">
                <div class="form-check">
                    <input type="checkbox" class="form-check-input" id="them">
                    <label class="form-check-label" for="them">Thêm</label>
                </div>
            </div>

            <div class="col-lg-2 mb-3">
                <div class="form-check">
                    <input type="checkbox" class="form-check-input" id="sua">
                    <label class="form-check-label" for="sua">Sửa</label>
                </div>
            </div>

            <div class="col-lg-2 mb-3">
                <div class="form-check">
                    <input type="checkbox" class="form-check-input" id="xoa">
                    <label class="form-check-label" for="xoa">Xóa</label>
                </div>
            </div>
        </div>
    </div>
    <div class="card-footer">
        <div class="d-flex align-items-center justify-content-between">
            <button type="submit" class="btn btn-primary">
                Lưu
            </button>
        </div>
    </div>
</div>

src/cungLaoDong/Views/Modules/Index.cshtml
@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <div class="d-sm-flex align-items-center justify-content-between">
            <h6 class="m-0 font-weight-bold text-primary">Danh mục chức năng</h6>
            <a asp-controller="Modules" asp-action="Add" class="d-none d-sm-inline-block">
                <i class="fas fa-download fa-sm text-white-50 pr-1"></i>
                &plus; Thêm
            </a>
        </div>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable">
                <thead>
                <tr class="text-primary">
                    <th>Chức năng</th>
                    <th>Ngày tạo</th>
                </tr>
                </thead>
                <tbody id="laborTable"></tbody>
            </table>
        </div>
    </div>
</div>